# Generated by Django 5.2.8 on 2025-11-26 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], max_length=10)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='institution_logos/')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('duration_years', models.IntegerField()),
                ('career_opportunities', models.JSONField(default=list)),
                ('required_skills', models.JSONField(default=list)),
                ('admission_criteria', models.TextField(blank=True)),
                ('tuition_fees_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tuition_fees_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('institutions', models.ManyToManyField(related_name='fields', to='catalog.institution')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.field')),
            ],
            options={
                'unique_together': {('user', 'field')},
            },
        ),
    ]
