# Generated by Django 5.2.8 on 2025-11-26 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('category', models.CharField(choices=[('academic_interests', 'Intérêts académiques'), ('perceived_skills', 'Compétences perçues'), ('professional_values', 'Valeurs professionnelles'), ('work_preferences', 'Préférences de travail')], max_length=50)),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('likert', 'Likert Scale (1-5)'), ('ranking', 'Ranking Preferences')], default='mcq', max_length=20)),
                ('options', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='OrientationTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('scores_data', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orientation_tests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_fields', models.JSONField()),
                ('compatibility_scores', models.JSONField(default=dict)),
                ('justification', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('orientation_test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation', to='orientation.orientationtest')),
            ],
        ),
        migrations.CreateModel(
            name='TestResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.JSONField()),
                ('orientation_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='orientation.orientationtest')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orientation.question')),
            ],
        ),
    ]
